spring.datasource.url=jdbc:mysql://localhost:3306/interview_platform
spring.datasource.username=root
spring.datasource.password=shee@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080